#!/bin/bash

DIR="$HOME/.config/sketchybar/"
ITEM_DIR="$DIR/items"
PLUGIN_DIR="$DIR/plugins"

FONT="JetBrainsMono Nerd Font"
ICON_FONT="SF Pro"

PADDING=3

source "$DIR/colors.sh"
source "$DIR/icons.sh"

BAR_PROPS=(
  height=40
  color=$BG_PRI_COLR
  border_width=1
  border_color=$BORDER_COLR
  shadow=off
  position=top
  sticky=on
  padding_right=15
  padding_left=15
  corner_radius=9
  y_offset=10
  margin=12
  blur_radius=15
  notch_width=0
)

DEF_PROPS=(
  updates=when_shown
  icon.font="$ICON_FONT:Regular:18.0"
  icon.color=$GREEN
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.font="$FONT:Semibold:13.0"
  label.color=$GREEN
  label.padding_left=$PADDING
  label.padding_right=$PADDING
  background.padding_right=$PADDING
  background.padding_left=$PADDING
  background.height=26
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=11
  popup.background.border_color=$BORDER_COLR
  popup.background.color=$BG_PRI_COLR
  popup.background.shadow.drawing=on
)

sketchybar --bar "${BAR_PROPS[@]}"
sketchybar --default "${DEF_PROPS[@]}"

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/focus.sh"

source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/sound.sh"
source "$ITEM_DIR/wifi.sh"

sketchybar --update

